# Generated by Django 3.2.3 on 2021-06-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(blank=True, default='profile/profile_none.png', null=True, upload_to='profile/'),
        ),
    ]
