# Generated by Django 3.2.3 on 2021-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
