# Generated by Django 3.2.3 on 2021-06-10 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tgl_lahir',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
