# Generated by Django 3.2.3 on 2021-05-29 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DALAM PEMERIKSAAN', 'DALAM PEMERIKSAAN'), ('DISETUJUI', 'DISETUJUI'), ('DITOLAK', 'DITOLAK')], default='DALAM PEMERIKSAAN', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('npp', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'NPP',
                'verbose_name_plural': 'LIST NPP',
                'ordering': ['-npp'],
            },
        ),
        migrations.CreateModel(
            name='toQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uuid', models.UUIDField(default=uuid.UUID('0535906f-450e-4f7a-ae95-8ef1a3f2cfdb'), editable=False)),
                ('img_svg', models.ImageField(upload_to='qrcode/')),
                ('tk_klaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.approvalhrd')),
            ],
        ),
        migrations.CreateModel(
            name='DataKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Format NIK Tidak Sesuai')])),
                ('kpj', models.CharField(max_length=11)),
                ('tgl_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=250)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'BELUM MENIKAH'), ('2', 'MENIKAH')], default='1', max_length=1)),
                ('nama_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_pasangan', models.DateField(blank=True, null=True)),
                ('nama_anak_s', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_s', models.DateField(blank=True, null=True)),
                ('nama_anak_d', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_d', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,9})$', 'Format NO HP TIDAK SESUA!!!')])),
                ('nama_rekening', models.CharField(max_length=100)),
                ('no_rekening', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{6,}$', 'No Rekening Harus Berupa Angka')])),
                ('file_kk', models.FileField(upload_to='kk/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_ktp', models.FileField(upload_to='ktp/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_buku_nikah', models.FileField(upload_to='buku-nikah/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('file_lain', models.FileField(blank=True, null=True, upload_to='lain/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|JPG|JPEG|pdf|PDF)', 'Only Support PDF dan JPG')])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.perusahaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DATA KLAIM',
                'verbose_name_plural': 'LIST DATA KLAIM',
            },
        ),
        migrations.CreateModel(
            name='DaftarHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.perusahaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LIST HRD',
            },
        ),
        migrations.AddField(
            model_name='approvalhrd',
            name='hrd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.daftarhrd'),
        ),
        migrations.AddField(
            model_name='approvalhrd',
            name='klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.dataklaim'),
        ),
    ]
