# Generated by Django 3.2.8 on 2021-10-15 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('3a06e326-96f9-4950-81fd-8c17bc28b6ec'), editable=False),
        ),
    ]
