# Generated by Django 3.2.3 on 2021-05-29 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('c249da3d-fd8d-4d1e-ac78-d4f2e9f92053'), editable=False),
        ),
    ]
