# Generated by Django 3.2.3 on 2021-06-09 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0002_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('91c560d0-fbcd-4665-b833-72014dddd59f'), editable=False),
        ),
    ]
