# Generated by Django 3.2.3 on 2021-05-29 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0002_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('d9377029-3802-4478-8d2f-589025c53384'), editable=False),
        ),
    ]
