# Generated by Django 3.2.3 on 2021-05-29 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0003_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('c1758e4d-eef7-49b3-9f5f-8a5f75cf287f'), editable=False),
        ),
    ]
