# Generated by Django 3.2.3 on 2021-06-10 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0003_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('1863693f-a416-4b87-8a4f-199f74cf466b'), editable=False),
        ),
    ]
