# Generated by Django 3.2.3 on 2021-05-31 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0004_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataklaim',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('b119f37b-4ce9-4275-bfa0-4d5482b25a57'), editable=False),
        ),
    ]
