# Generated by Django 3.2.3 on 2021-06-06 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0005_auto_20210531_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('0690bc9c-e9e1-4738-9312-b7d8901cd55d'), editable=False),
        ),
    ]
