# Generated by Django 3.2.3 on 2021-05-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0006_alter_dataklaim_no_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='toQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uuid', models.CharField(max_length=40)),
                ('img_svg', models.ImageField(upload_to='img/qrcode/')),
                ('tk_klaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.dataklaim')),
            ],
        ),
    ]
