# Generated by Django 3.2.3 on 2021-05-24 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0007_toqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('396e5b42-cd3c-42fd-b15f-4323b2a35b80'), editable=False),
        ),
    ]
