# Generated by Django 3.2.3 on 2021-05-24 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0008_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('12a558ce-0e3c-44ab-86e9-5f2a9f322067'), editable=False),
        ),
    ]
