# Generated by Django 3.2.3 on 2021-05-25 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0009_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='tk_klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.approvalhrd'),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('9de19666-7eca-4e17-828a-a318d6c3574a'), editable=False),
        ),
    ]
