# Generated by Django 3.2.3 on 2021-05-25 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0010_auto_20210525_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='tk_klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.dataklaim'),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('60ab309b-4e13-44e7-83fe-e6c7b47c1aaf'), editable=False),
        ),
    ]
