# Generated by Django 3.2.3 on 2021-05-25 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0011_auto_20210525_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='tk_klaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.approvalhrd'),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('c4f1bbc7-fed6-44f1-a4a3-123820c0c250'), editable=False),
        ),
    ]
