# Generated by Django 3.2.3 on 2021-05-25 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0012_auto_20210525_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('56897b6c-b5df-4f7f-bc54-857fa95d1b4a'), editable=False),
        ),
    ]
