# Generated by Django 3.2.3 on 2021-05-25 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0013_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('d46a4721-8340-4943-8931-8cf4a0a9cca6'), editable=False),
        ),
    ]
