# Generated by Django 3.2.3 on 2021-05-25 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0014_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='img_svg',
            field=models.ImageField(upload_to='qrcode/'),
        ),
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('0782dfc5-cf43-47e0-9c90-929f0a2636ca'), editable=False),
        ),
    ]
