# Generated by Django 3.2.3 on 2021-05-26 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0015_auto_20210526_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('fbea5853-422b-47a5-a143-286dc934744d'), editable=False),
        ),
    ]
