# Generated by Django 3.2.3 on 2021-05-27 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0016_alter_toqrcode_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toqrcode',
            name='url_uuid',
            field=models.UUIDField(default=uuid.UUID('6377e260-6539-4e90-9a69-0ec65b2a83ac'), editable=False),
        ),
    ]
